# Generated by Django 3.2.7 on 2021-09-22 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('init_login', models.BooleanField(default=False)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('pan_no', models.CharField(max_length=10)),
                ('aadhar_reg', models.BooleanField(default=False)),
                ('cust_crn_no', models.CharField(max_length=8)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('prof_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=10)),
                ('acc_bal', models.DecimalField(decimal_places=4, max_digits=7)),
                ('acc_type', models.CharField(choices=[('SAV', 'Savings'), ('CUR', 'Current'), ('FD', 'Fixed Deposit'), ('RD', 'Recurring Deposit')], max_length=50)),
                ('acc_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customerprofile')),
            ],
        ),
    ]
