# Generated by Django 3.2.7 on 2021-09-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customerprofile_prof_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
