# Generated by Django 3.2.7 on 2021-09-22 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210922_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RTGS', 'RTGS'), ('NEFT', 'NEFT')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=7)),
                ('trxn_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('successful', 'successful'), ('failed', 'failed')], max_length=50)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='main.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.account')),
            ],
        ),
    ]
