# Generated by Django 3.2.7 on 2021-09-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_transaction_trxn_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_bal',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
