# Generated by Django 3.2.7 on 2021-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
